package analyst;
 
import java.util.ArrayList;
import com.dataframe.DataFrame;
import com.dataframe.DataFrameIndexException;
import com.dataframe.DataFrame.*;
import com.factengine.*;
import com.factengine.commanders.*;
import com.factengine.analysisdescriptors.*;
import com.factengine.factmodels.*;
import com.factengine.datasetdescriptors.*;
import com.datautils.*;

 


rule "choose rows to be imputed"
salience 1000
	no-loop
	when	
		$row : FactRow(numberMissingValues>0 , numberMissingValues<2)
		$impCommander : ImputationCommander()
	then
	    System.out.println($row.getRow()); 
	    System.out.println("choose rows to be imputed");
	    $impCommander.addRow($row.getRow());
end


rule "impute rows"
salience 900
	no-loop
	when
		$df: DataFrame()
		$impCommander : ImputationCommander()
	then
		System.out.println("impute rows");
		$impCommander.impute($df);
end



rule "choose columns to remove"
salience 800
	no-loop
	when
		$col: FactColumn(PercentageMissingValues>1);
		$colCommander: ColumnRemovalCommander()
	then
		System.out.println("choose columns to remove: "+$col.getColumn());
		$colCommander.addColumn($col.getColumn());
end



rule "removal of columns"
salience 700
	no-loop
	when
		$df: DataFrame()
		$colCommander: ColumnRemovalCommander()
	then
		System.out.println("removal of columns");
		$colCommander.removeColumns($df);
end



rule "choose rows to be removed"
salience 600
	no-loop
	when	
		$row : FactRow(numberMissingValues>1)
		$rowRemovalCommander : RowRemovalCommander()
	then
		System.out.println("choose rows to be removed: "+$row.getRow());
	    $rowRemovalCommander.addRow($row.getRow());
end



rule "removal of rows"
salience 500
	no-loop
	when	
		$df: DataFrame()
		$rowRemovalCommander : RowRemovalCommander()
	then
		System.out.println("removal of rows");
		System.out.println($df.getNumberColumns());
		System.out.println($df.getRows(1,15));
	    $rowRemovalCommander.removeRows($df);	  	
end



rule "clean up names"
salience 400
	no-loop
	when	
	
	then
	  	
end

rule "detect low variance columns"
salience 350
	no-loop
	when	
	
	then
	  	
end

rule "remove low variance columns"
salience 340
	no-loop
	when	
	
	then
	  	
end

rule "detect outliers"
salience 300
	no-loop
	when	
	
	then
	  	
end



rule "remove outliers"
salience 200
	no-loop
	when	
	
	then
	  	
end

/*
rule "factfactory impute"
	no-loop
	when	
		$row : FactRow(numberMissingValues>0 , numberMissingValues<5)
		$impCommander : ImputationCommander()
	then
	    System.out.println($row.getRow()); 
	    $impCommander.addRow($row.getRow());
end
*/